### ISSUE TITLE
感觉不够淫乱，可以更淫乱一点吗？

### ISSUE THREAD

**Issue by LoTwT** [kifuan/node-yinglish#4]

**Comment by LoTwT** [comment]
能不能支持调整淫乱系数，让结果的期望总体更淫乱捏？

**Comment by kifuan** [comment]
不是能调吗

![W$XN%`J~WPGPIR%W)HMFR3W](https://user-images.githubusercontent.com/61240774/200257433-4fb1134b-1eda-42ff-93ef-35bc8e385331.jpg)

https://github.com/kifuan/node-yinglish/blob/master/src/index.ts#L39

**Comment by LoTwT** [comment]
https://github.com/kifuan/node-yinglish/blob/52127b84ffc2baf9d21295083a91b62d71acf0fa/src/index.ts#L10

透的不够彻底捏

**Comment by LoTwT** [comment]
> 不......不行............那里不行。

这种感觉感觉就不是很淫乱捏，想想办法优化捏

**Comment by LoTwT** [comment]
#5
